### PR TITLE
feedtype => feedFormat

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by Powersource** [comment]
Did we have a vague idea of how to potentially migrate away from a `classic` invitations feed or will this be the thing that locks us to classic?

**Comment by Powersource** [comment]
I guess we're largely already locked to classic for current users. So when a future client comes along and doesn't want to use classic, they'll just have to update this spec to be able to use something else so no biggie

**Comment by staltz** [comment]
Yes invitations can be migrated (by tombstoning the classic feed, starting a new invitations feed with the new feed format, and then copy-pasting all msgs from old to new). So can the groupFeed

**Comment by Powersource** [comment]
There'll be tangle issues though?

**Comment by Powersource** [comment]
> they'll just have to update this spec to be able to use something else so no biggie

I guess as long as they're fine with not talking with existing users :grimacing:

**Comment by arj03** [comment]
We haven't specified this properly but in theory i don't see a problem with a feed being tombstoned meaning the messages are still relevant, bit the feed should not be extended and then continuing on another invitations feed. This is not that different from migrating your main feed to a new feed format. Tangles should still work across different feed formats thanks to URI s

**Review by mixmix — APPROVED** [review]

**Pull request merged**
