### PR TITLE
Clarify encrypted groupFeed announcement message

### PR DESCRIPTION
**Pull request by staltz**
- [ ] use metafeed/update instead of metafeed/add/existing

### CODE REVIEW

**Comment by arj03** [comment]
What I had in mind was that instead of encrypting the announce to only the group you would encrypt it to also X other as a DM. Using our new scheme this would then be encrypted using the mirror nibble. Interesting case that this then requires the other peer to have that nibble. You could add more feeds using metadata update on the feed.

**Comment by staltz** [comment]
> What I had in mind was that instead of encrypting the announce to only the group you would encrypt it to also X other as a DM. Using our new scheme this would then be encrypted using the mirror nibble.

What about the first groupFeed (from the person who created the group)? It doesn't have mirror feeds on other peers because those other peers haven't created the groupFeed yet.

But this PR is mostly about enabling sympathetic replication. If the metafeed/add/derived is encrypted, then peers who are not involved in the group would not know about the existence of the groupFeed, and could not replicate it sympathetically. This is why I'm considering publishing an unencrypted metafeed/add/existing so that other peers can know a groupFeed without knowing what group it's about.

**Comment by arj03** [comment]
Yes if we want public sympathetic replication we can do this, but then use update instead because otherwise the feed exists twice for people in the group.

**Comment by staltz** [comment]
Ooh, now I see what you mean with `update`, it's the little-known `metafeed/update` message. By the way, there's only one quick mention of `metafeed/update` on the spec, and there's nothing implemented for it in `ssb-meta-feeds`.

**Comment by staltz** [comment]
More thoughts about this PR: maybe sympathy shouldn't be specified as a `metafeed/update` on the same shard (for many reasons). Maybe we should have a `sympathy` content feed which publishes very simple messages that have just the feed ID for all the feeds that the user would like others to "boost replication".

**Comment by arj03** [comment]
I like that idea. This way we can also formalize a v1 of how that is going to work.

**Comment by staltz** [comment]
And, it wouldn't leak what shard the group feed is on. I don't know if it's a problem to leak the shard feed or not, but if we don't **have** to leak it, then that's better.

**Comment by staltz** [comment]
Closing this PR because we settled on a different idea: a "sympathy" feed that publishes only IDs of other leaf feeds that would be nice to replicate. We gotta find another spec place where to put that definition.

**Pull request closed without merging**
